### ISSUE TITLE
@types Vs typings

### ISSUE THREAD

**Issue by Rajiv-Kulkarni** [StrikeForceZero/react-typescript-boilerplate#6] opened 2017-02-23 03:30 UTC
# React Boilerplate
## Issue Type
Not a bug.

## Description
What's the difference between the old fashioned:
"typings": "^2.1.0"
Versus the new syntax:
    "@types/classnames": "^0.0.32",
    "@types/node": "^7.0.4",
    "@types/react": "^15.0.6",
    "@types/react-dom": "^0.14.22",
    "@types/react-redux": "^4.4.36",
    "@types/react-router": "^3.0.0",
    "@types/react-router-redux": "^4.0.39",
    "@types/redux-actions": "^1.2.2",
    "@types/webpack": "^2.2.4",
    "@types/webpack-env": "^1.13.0"
etc. I have seen elsewhere in the package.json? Thanks.

**Comment by StrikeForceZero** [comment] 2017-02-24 16:19
`@types` is the new official typing's via npm modules, supported by typescript. `typings` was the old method that pulled from the DefinitelyTyped Repo directly.

I sometimes use both because there are some transition regressions I still need to work out and missing types.

side-note: could you edit your issue to only have the text inside the description? the rest is kind of noisy.

**Comment by Rajiv-Kulkarni** [comment] 2017-02-24 16:28
So eventually you will be switching to the new syntax? The question always is how long will the old one be supported. Thanks.

**Comment by StrikeForceZero** [comment] 2017-02-24 16:57
I am aiming to fully transition to the new syntax to minimize bloat. Are you asking about support for this repo? or support for `typings` in general?

It should remain supported as long as the DefinitelyTyped Repo is alive and the npm module `typings` stays published.

**Comment by Rajiv-Kulkarni** [comment] 2017-02-24 17:08
Support for typings Sir. Thanks.

**Comment by StrikeForceZero** [comment] 2017-04-07 01:00
closing in favor of https://github.com/StrikeForceZero/react-typescript-boilerplate/commit/9494e4e4cc8273f1e7c2ea7b1cf9eb5a21d886f1

**Closed as completed by StrikeForceZero** 2017-04-07 01:00 UTC
Labels: question
